Add CSI work diary module
Rick00Kim/Slack_Automator pull request #1
Opened 2021-04-24 10:56 UTC by Rick00Kim

Spec
1. Python 3.8.2
2. Main libraries
    - Flash framework
    - Selenium
    - Slack client
3. Deploy Server
    - Heroku(No using database)

2021-04-24 11:04 UTC, Rick00-Helper requested changes
Please check some code

2021-04-24 11:04 UTC, Rick00-Helper commented on csi_work_diary/app/message_format/app_view.json
> +}
EOF

2021-04-24 11:04 UTC, Rick00-Helper commented on csi_work_diary/app/message_format/hotel_list.json
> +[
Never use

2021-04-24 11:04 UTC, Rick00-Helper commented on csi_work_diary/app/message_format/new_user.json
> +}
EOF

2021-05-02 12:46 UTC, Rick00Kim commented
This pull request will merge after complete to-do.

2021-05-02 15:04 UTC, Rick00Kim commented on csi_work_diary/app/message_format/hotel_list.json
> +[
#2 Resolved

2021-05-02 15:09 UTC, Rick00Kim commented on csi_work_diary/app/message_format/app_view.json
> +}
49f6363 resolved

2021-05-02 15:09 UTC, Rick00Kim commented on csi_work_diary/app/message_format/new_user.json
> +}
49f6363 resolved

2021-05-02 15:10 UTC, Rick00-Helper approved these changes
LGTM

2021-05-02 15:11 UTC, Rick00Kim commented
@Rick00-Helper 
Thank you for check.
I will merge this pull request.

2021-05-02 15:11 UTC, merged